name : CI Pipeline - Main
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GIT__BRANCH      : 'main'
  RELEASE_TYPE     : 'major'
  PACKAGE_NAME     : 'osbot_electron'

jobs:

  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "run-tests"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pytest__run-tests@dev

  increment-tag:
    name: Increment Tag - Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-tests

  publish-to-pypi:
    if: False
    name: "Publish to: PYPI"
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__twine__publish@dev
    needs:
      - increment-tag

  # Build universal macOS DMG
  electron__build-dist__macos-universal:
    name: "Build macOS Universal DMG"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "build-macos-universal-dmg"
        uses: ./.github/actions/electron__build-dist__macos
        with:
          electron-app-path: 'electron_app'
          artifact-name: 'macos-universal-dmg'
          mac-certs: ${{ secrets.MAC_CERTS }}
          mac-certs-password: ${{ secrets.MAC_CERTS_PASSWORD }}
          apple-id: ${{ secrets.APPLE_ID }}
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
          team-id: ${{ secrets.APPLE_TEAM_ID }}
    needs:
      - increment-tag
